#!/bin/bash


## Load the required modules
module load mpt
module load intel-compilers-19

## compile


## compile with MPI:
mpicxx amair_matmul.cpp  -o amair_matmul.exe

## remove object files if there is any!:
# rm *.mod
# rm *.o

